[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.2.1"
edition = "2021"
license = "MIT"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
sdl2 = { version = "0.37", features = ["image", "ttf", "mixer"] }
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }

gal-config = { path = "crates/gal-config" }
gal-platform = { path = "crates/gal-platform" }
gal-text = { path = "crates/gal-text" }
gal-script = { path = "crates/gal-script" }
gal-audio = { path = "crates/gal-audio" }
gal-save = { path = "crates/gal-save" }
gal-ext = { path = "crates/gal-ext" }
gal-render = { path = "crates/gal-render" }
gal-ui = { path = "crates/gal-ui" }
gal-engine = { path = "crates/gal-engine" }

# 全家族统一在 release 收尾：LTO+strip（游戏 bin 继承）
[profile.release]
opt-level = 3
lto = true
strip = true

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
undocumented_unsafe_blocks = "warn"
redundant_clone = "warn"
single_char_pattern = "warn"
manual_let_else = "warn"
